module.exports = {
	'SMS' : {
		'WELCOME_MESSAGE' : "{!{name}!} have salary of {!{amount}!} rupees per day",
	},
	'MESSAGE' : {
		'GENERAL_CATCH_MESSAGE' : 'Something went wrong. Please try again later',
		'TWILIO_SMS_SEND_SUCCESS' : 'SMS sent successfully',
		'EMAIL_ALREADY_EXISTS' : 'Email already exists',
		'USER_TYPE_REQUIRED' : 'User type is required',
		'NEW_USER_CREATED' : 'New user created successfully',
		'UNAUTHRIZED_LOGIN' : 'Unauthorized login',
		'USER_DETAILS_NOT_AVAILABLE' : 'User details not available',
		'INVALID_PASSWORD' : 'Invalid password',
		'PASSWORD_MIN_LENGTH' : 'Password must be 6 charachter long',
		'PASSWORD_UPDATE_SUCCESS' : 'Password updated successfully',		
		'PROFILE_FETCH_SUCCESS' : 'Profile retrived successfully',		
		'PROFILE_UPDATE_SUCCESS' : 'Profile updated successfully',		
		'LOGOUT_FAILED' : 'User logout failed',		
		'LOGOUT_SUCCESS' : 'User logout successfully',		
		'MULTIPLE_DEVICE_LOGIN_NOT_ALLOWED' : 'Multiple device login are not allowed, please logout from device first',
		'FORGOTPASSWORD_EMAIL_SUCCESS':'Email has been sent successfully.',
		'FORGOTPASSWORD_EMAIL_FAIL':'Error while sending email.',
		'FORGOTPASSWORD_OTP_SUCCESS': 'OTP has been sent successfully.',
		'FORGOTPASSWORD_OTP_FAIL': 'Error while sending OTP.',
		'TITLE_ALREADY_EXISTS': 'Title already exists.',
		'EMAIL_FORMAT_CREATED_SUCCESS': 'Email format created successfully.',
		'EMAIL_FORMAT_UPDATED_SUCCESS': 'Email format updated successfully.',
		'NO_EMAIL_FORMAT_EXISTS': 'No email format exists.',
		'EMAIL_TEMPLATE_RETRIEVE': 'Email Template retrieve successfully.',
		'EMAIL_TEMPLATE_DELETED': 'Email Template deleted successfully.',
		'SMS_TEMPLATE_CREATED_SUCCESS': 'SMS Template created successfully.',
		'SMS_TEMPLATE_UPDATED_SUCCESS': 'SMS Template updated successfully.',
		'NO_SMS_TEMPLATE_EXISTS': 'No SMS template exists.',
		'NO_SMS_FORMAT_EXISTS': 'No SMS format exists.',
		'SMS_TEMPLATE_RETRIEVE': 'SMS Template retrieve successfully.',
		'SMS_TEMPLATE_DELETED': 'SMS Template deleted successfully.',
	}
}